baseurl = "https://MikaeelMF.github.io"
title = "Mikaeel Mayeli"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true


[params]
  author = "Mikaeel Mayeli"
  info = "Tinkering with interesting stuff"
  description = "Mikaeel Mayeli's personal website"
  keywords = "blog,mikaeel,mikaeelmayeli,mayeli,personal,mikaeil,mikaeilmayeli"
  avatarurl = "images/avatar.jpg"

  favicon_32 = "images/favicon-32-32.png"
  favicon_16 = "images/favicon-16-16.png"
  touchIcon = "images/touchIcon.png"

  hideFooter = false
  hideCredits = false
  hideCopyright = false
  since = 2021

  enableTwemoji = true

  colorScheme = "dark"
  hidecolorschemetoggle = true

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/MikaeelMF/"

# Menu links
[[menu.main]]
  name = "Publications"
  weight = 1
  url = "pub/"
[[menu.main]]
  name = "Blog"
  weight = 2
  url = "blog/"
[[menu.main]]
  name = "About"
  weight = 3
  url = "about/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true